### ISSUE TITLE
オンボーディング手順のどこかに /github signin を追記

### ISSUE THREAD

**Issue by riscait** [altive/handbook#112]
Slackにて `/github signin` を実行してサインインすると…

SlackのGitHubアプリが投稿した内容にGitHubメンションがあると、Slack上ではSlackのメンションに変換される。

例：
GitHub: @riscait -> Slack: @村松龍之介

これを行うことを、オンボーディング手順のどこか（SlackについてかGitHubについて記載しているところにだと分かりやすそう）に追記する。

**Comment by boywithdv** [comment]
The issue took 1 days.
